server:
  # 设置tomcat
  jetty:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 50
  # 指定端口
  port: 80
  # 指定项目的ContextPath路径
  servlet:
    context-path: /userapi
spring:
  # 字符编码过滤器配置（CharacterEncodingFilter）
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # 日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 配置上传
  multipart:
    enabled: true
    # 每个文件限制为10M
    max-file-size: 50MB
    # 单词请求所有文件容量不能大于100MB
    max-request-size: 2000MB
  # 包含dao的yml配置文件,对应的是application-xxx.yml文件的xxx名称
  profiles:
    include: dao, service
