spring:
  #消息队列
  rabbitmq:
    addresses: www.88k88.cn
    # 连接端口,默认5672
    port: 5672
    username: topyin
    password: qq520340
    # 虚拟主机地址，默认为"/"
    virtual-host: /
    # 设置连接诶超时时间
    connection-timeout: 5000
    # 配置消费者监听设置
    listener:
      simple:
        # 最小消息消费线程数
        concurrency: 2
        # 最大消息消费线程数
        max-concurrency: 5
        # 限流，每个消费线程能从队列获取的消息数量
        prefetch: 2
        # 消息签收模式，消息被消费后会回馈一条确认信息给rabbitmq
        # 可以设置为自动或者手动签收，这里设置为手动
        acknowledge-mode: manual
  #内存数据库
  redis:
    host: www.88k88.cn
    port: 6379
    password: qq520340
    database: 1
    timeout: 30000s
    #连接池配置
#    lettuce:
#      pool:
#        # 最大连接数
#        max-active: 20
#        # 最大空闲连接
#        max-idle: 8
#        # 最小空闲连接
#        min-idle: 5
#        # 建立连接最大等待时间
#        max-wait: 2000
#        # 每间隔多少毫秒运行一次空闲连接回收
#        time-between-eviction-runs: 60000