server:
  # 设置tomcat
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 50
  # 指定端口
  port: 8080
  # 指定项目的ContextPath路径
  servlet:
    context-path: /userapi
spring:
  # 字符编码过滤器配置（CharacterEncodingFilter）
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # 日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 配置上传
  multipart:
    enabled: true
    # 每个文件限制为10M
    max-file-size: 50MB
    # 单词请求所有文件容量不能大于100MB
    max-request-size: 2000MB
  # 包含dao的yml配置文件,对应的是application-xxx.yml文件的xxx名称
  profiles:
    include: dao, service

  rabbitmq:
    addresses: 127.0.0.1
    # 连接端口,默认5672
    port: 5672
    # 设置登陆认证的账号密码，默认为guest
    username: crab
    password: 123456
    # 虚拟主机地址，默认为"/"
    virtual-host: /
    # 设置连接诶超时时间
    connection-timeout: 5000
    # 配置消费者监听设置
    listener:
      simple:
        # 最小消息消费线程数
        concurrency: 2
        # 最大消息消费线程数
        max-concurrency: 5
        # 限流，每个消费线程能从队列获取的消息数量
        prefetch: 2
        # 消息签收模式，消息被消费后会回馈一条确认信息给rabbitmq
        # 可以设置为自动或者手动签收，这里设置为手动
        acknowledge-mode: manual